server:
  port: 8082

spring:
  application:
    name: PATIENT-SERVICE
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/data_micro
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
